### PR TITLE
Fix #102: Remove "starting" from presentation timestamp wording in duration change algorithm.

### LINKED ISSUE #102: "starting presentation timestamp" in duration change algorithm text is confusing. Drop "starting".
The [Duration Change](http://w3c.github.io/media-source/#duration-change-algorithm) algorithm no longer links to the [Range Removal](http://w3c.github.io/media-source/#sourcebuffer-range-removal) algorithm (the change was made in response to issues #15 and #26, I think).

The [End of Stream](http://w3c.github.io/media-source/#end-of-stream-algorithm) algorithm tells the user agent to update the duration to the _highest end time reported by the buffered attribute_. The intent seems to be to truncate the duration to the content effectively buffered.

Am I right to assume that the track buffer ranges of a SourceBuffer remain untouched when the duration is truncated? If so, am I right to think that the duration may be set to a much larger value when `endOfStream()` is called as in the example below?

```javascript
// Let's say mediaData holds 10s of media content
var sourceBuffer = mediaSource.addSourceBuffer(mimeType);
sourceBuffer.appendBuffer(mediaData);
sourceBuffer.onupdateend = function () {
  // sourceBuffer.buffered.end(0) should now equal 10

  // Truncating the duration no longer removes any buffered frame,
  // so sourceBuffer.buffered.end(0) should still equal 10 after next line
  mediaSource.duration = 2;

  // End of stream algorithm sets duration to the highest end time reported
  // by the buffered attribute, sourceBuffer.buffered.end(0) in this example
  mediaSource.endOfStream();

  // mediaSource.duration should now equal 10. Is this the intended behavior?
}
```

### PR DESCRIPTION
**Pull request by wolenetz**

### CODE REVIEW

**Comment by wolenetz** [comment]
@jdsmith3000 Please take a look. Thanks!

**Comment by wolenetz** [comment]
@jdsmith3000 friendly ping

**Comment by wolenetz** [comment]
@jdsmith3000 please review this

**Comment by wolenetz** [comment]
I'll land this later today, barring any objections raised before then.

**Comment by jdsmith3000** [comment]
Post merge:  Change is correct.  LGTM.

**Comment by wolenetz** [comment]
Thank you.

**Pull request merged**
