### PR TITLE
Change from TrackDefault.kinds to TrackDefault.getKinds

### PR DESCRIPTION
**Pull request by plehegar**
Fix for #91

### CODE REVIEW

**Comment by wolenetz** [comment]
LGTM. Editorial changes (non-substantive) may follow. Thanks for putting this together, @plehegar 
I'll merge it shortly.

**Comment by jdsmith3000** [comment]
Late, but LGTM too.

What's the status of @wolenetz's proposed addition to the at risk features here?

**Comment by jdsmith3000** [comment]
Actually, two questions:

1. How do we tell the returned value for `getKinds()` is a `kinds`object?
2. Is the legacy constructor entry for `sequence<DOMString> kinds` a bug?

```
[ Constructor (TrackDefaultType type, DOMString language, DOMString label, sequence<DOMString> kinds, optional DOMString byteStreamTrackID = "")]
interface TrackDefault {
    readonly        attribute TrackDefaultType type;
    readonly        attribute DOMString        byteStreamTrackID;
    readonly        attribute DOMString        language;
    readonly        attribute DOMString        label;
    sequence<DOMString> getKinds ();
};
```

**Comment by wolenetz** [comment]
Are either of those substantive? Or can we discuss and fix after today's
deadline?

**Pull request merged**
