### PR TITLE
Update editors

### PR DESCRIPTION
**Pull request by wolenetz**
In addition to editors update, this includes the content in https://github.com/w3c/media-source/pull/2, too. I can update this pull request to just include the editors update once that other pull request has been merged.

### CODE REVIEW

**Comment by wolenetz** [comment]
@acolwell and @adrianba, is it customary to move former editors to contributors, or is the editors list purely additive over time? This pull request assumes the former, but I could be totally wrong.

**Comment by wolenetz** [comment]
Also, @jdsmith3000, fyi - I've included you in the editors list update contained in this pull request (assuming jdsmith3000 == Jerry Smith from Microsoft, of course.)

**Comment by paulbrucecotton** [comment]
I suggest you leave Adrian and Aarron as Editors but indicate that their term ended in April 2015.  See how Adrian is listed on EME. http://www.w3.org/TR/2015/WD-encrypted-media-20150331/

**Comment by acolwell** [comment]
Matt. You'll probably need to rebase this change to ToT once you've updated it like Paul proposed. I merged your other request before looking at this one so the bug fix in this CR already is in the repo now.

**Comment by wolenetz** [comment]
Thank you, acolwell@ and @paulbrucecotton. I've rebased and updated this pull request per your proposals.

**Comment by wolenetz** [comment]
I need to also remove myself from the mseContributors, and I spotted a couple formatting issues in my recent updates to the Revision History section. Please don't merge this pull just yet.

**Comment by wolenetz** [comment]
This pull request is now ready for review and merge.

**Pull request merged**
