### PR TITLE
Fixes issue #66

### PR DESCRIPTION
**Pull request by wolenetz**
- Adds EventHandler attributes to MediaSource, SourceBuffer, and
  SourceBufferList
- Updates most recent CR publish date (3 May 2016) in source.
- Minor source whitespace and changelist formatting fixes.

### CODE REVIEW

**Comment by wolenetz** [comment]
@jdsmith3000 please take a look. This one's simple enough relative to #73 that I'd like to land this one first and then rebase #73 on the result. Thanks! @foolip, too as FYI.

**Comment by wolenetz** [comment]
Actually, hold on this review briefly while I add attribute descriptions to each of these handlers to reference their respective events. FYI - I'm using https://w3c.github.io/web-animations/#the-animation-interface as a loose template for how to do this.

**Comment by wolenetz** [comment]
OK. This is now ready for your review, @jdsmith3000 
Thanks again.

**Comment by jdsmith3000** [comment]
@Wolenetz This change looks complete and accurate to me.  It is ready to merge.  Please confirm you are done with your commits and I will do the merge.

**Comment by jdsmith3000** [comment]
Pull request merged as commit 1e4b68c15c327ba96c8f7fffa21b8754bf324499.

**Comment by wolenetz** [comment]
@jdsmith3000 Thanks for merging (I was OoO as I had communicated in advance last week.)

**Pull request merged**
