### PR TITLE
Fix issue 25 and fix the publish date to be in 2016

### PR DESCRIPTION
**Pull request by wolenetz**
At long last, here's a PR to address issue #25 including restricting compliant implementations to only need to do the conservative removal path (using random access points for the removal, rather than allowing the more granular route). These follow comments on issue #25.
This change also fixes the publish date yet again (to be in 2016!!) :)

### CODE REVIEW

**Comment by wolenetz** [comment]
@jdsmith3000 Please take a look and let me know if this looks good to merge. I'll do the merge though, please :)

**Comment by wolenetz** [comment]
I've rebased it on top of a separate fix I just landed that fixed the index.html publishDate. No other changes since original PR last night.

**Comment by wolenetz** [comment]
@jdsmith3000 friendly ping :)

**Comment by jdsmith3000** [comment]
I believe this is complete and accurately implements the agreed issue fix, though there are small typos in step 15 of **Coded Frame Processing**:

Is:

> Remove all possible decoding dependencies **_of the coded frames frames_** removed in the previous two steps by removing all coded frames between those frames removed in the previous two steps and the next random access point after those removed frames. 

s.b.:

> Remove all possible decoding dependencies **_on the coded frames_** removed in the previous two steps by removing all coded frames between those frames removed in the previous two steps and the next random access point after those removed frames

.

**Comment by wolenetz** [comment]
Thanks for the review. I agree with your typo fix (s.b.:...). I'll make that fix and merge this soon.

**Comment by wolenetz** [comment]
Hmm. When searching for similar phrasing, I found another instance of the same problem (I believe) tracked by issue 25 in the coded frame *removal* algorithm. I'll make that further adjustment in this PR and re-request review.

**Comment by wolenetz** [comment]
@jdsmith3000  Please take a final look at the updated PR commit ddd5086.

**Comment by wolenetz** [comment]
I'll update with simple rebase shortly, now that I've merged #64 into the repo.

**Comment by wolenetz** [comment]
@jdsmith3000 please take a final look at the updated PR commit 81b27bc

**Comment by wolenetz** [comment]
@jdsmith3000 FWIW, w3c has a handy html diff tool. This link [1] shows the diff of commit 81b27bc to the current editor's draft:
[1] http://services.w3.org/htmldiff?doc1=http%3A%2F%2Fw3c.github.io%2Fmedia-source%2F&doc2=http%3A%2F%2Frawgit.com%2Fwolenetz%2Fmedia-source%2F81b27bc84bc64419abff2b8235dc66418ba53a5a%2Findex.html

**Comment by jdsmith3000** [comment]
Looks good.

Thanks for the diff suggestion.

**Pull request merged**
