### PR TITLE
Fix for #78: Update reference from HTML5.0 to HTML 5.1 

### PR DESCRIPTION
**Pull request by plehegar**
Notes:
- error definition are in webidl spec
- media controller got removed from HTML 5.1
- also fix a ref to High Resolution Time

Some HTML 5.1 links will be reported as broken by the link check. It should be fixed once HTML 5.1 WD gets updated on June 2.

### CODE REVIEW

**Comment by wolenetz** [comment]
Thanks for preparing this. I'll take a look next week. @jdsmith3000 please also take a look.

**Comment by paulbrucecotton** [comment]
@wolenetz, @jdsmith3000, @mwatson2 

Can one of the MSE Editors accept this PR?

**Comment by wolenetz** [comment]
I'll review this shortly (tomorrow).

**Comment by jdsmith3000** [comment]
LGTM

This change affects numerous links in the MSE spec.  I did a pass through the spec to check the links, and reviewed the changes to media-source.js as well.  I believe it's complete and ready to merge.

**Comment by jdsmith3000** [comment]
@wolenetz If this PR is still active on Monday, I will do the merge.

**Comment by wolenetz** [comment]
OK. Please give me through about noon on Monday (PDT) to get any comments into the PR.

**Comment by wolenetz** [comment]
Before I get deep into the review, note that this PR will need to be adjusted: media-source.html is *not* the version to update when regenerating from respec. Rather, replace index.html with the regenerated output from media-source-respec.html.

**Comment by wolenetz** [comment]
I'm going to add a commit that re-regenerates the draft into index.html shortly.

**Comment by wolenetz** [comment]
Once I complete my review, if all looks good, I'll do the merge. ETA: today.

**Comment by wolenetz** [comment]
I'll use the steps at http://stackoverflow.com/a/33907518 to inherit and update this PR.

**Comment by jdsmith3000** [comment]
@Wolenetz Are you planning to resolve the merge conflicts with this PR or pass them back to @plehegar to be resolved by him?  I suspect the latter would be simplest.

@plehegar Can you get this merge ready early tomorrow?

**Comment by wolenetz** [comment]
I'm working on this now.

**Comment by wolenetz** [comment]
Rebased to current gh-pages and updated the changelog. Will regenerate the draft into index.html and undo the media-source.html (555b847) portion. Then I'll land this.

**Pull request merged**
