### PR TITLE
Use internal slots for various MediaSource and SourceBuffer object state

### LINKED ISSUE #286: Editorial: Modernize to use internal slots instead of "internal ... variable"
As @tidoust noted in a recent review comment (https://github.com/w3c/media-source/pull/282#discussion_r664101655), internal slots are how specs currently describe internal object variable state that is meaningful to the spec.

The existing MSE spec has a few of these which need updating (SourceBuffer append state is just one example).

### PR DESCRIPTION
**Pull request by wolenetz**
Note, track buffers and their internal state remain as "variables", not internal slots, in the spec for now. Later refactoring might make them internal slots too, though at lower priority.

This partially fixes #286

***
<a href="https://pr-preview.s3.amazonaws.com/wolenetz/media-source/pull/295.html" title="Last updated on Sep 3, 2021, 12:09 AM UTC (71c80b2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/media-source/295/6efee8e...wolenetz:71c80b2.html" title="Last updated on Sep 3, 2021, 12:09 AM UTC (71c80b2)">Diff</a>

### CODE REVIEW

**Comment by wolenetz** [comment]
@tidoust / @mwatson2 - Am I correct that the current external reference by the BSF Registry of `generate timestamps flag` via the helpers in media-source.js would be more stable if instead that registry used xref to reference the media-source spec, and {{SourceBuffer/[[generate timestamps flag]]}} respec syntax to reference the definition of that internal slot? For now at least, I *think* I've updated media-source.js in this PR to use the updated fragment for this former variable that is now an internal slot.

Also, please review soon if you could, as rebasing this could get ugly since it touches quite a number of lines. Thanks!

**Review by tidoust — APPROVED** [review]
This all looks good to me! The need to write terms surrounded by `[[ ]]` and `{{ }}` in the source spec is not necessarily fantastic from an authoring perspective. Hopefully, the ability to better track and validate references to these terms makes it acceptable.

> @tidoust / @mwatson2 - Am I correct that the current external reference by the BSF Registry of generate timestamps flag via the helpers in media-source.js would be more stable if instead that registry used xref to reference the media-source spec, and {{SourceBuffer/[[generate timestamps flag]]}} respec syntax to reference the definition of that internal slot?

Yes and you were right to flag the definition of the internal slot with a `data-export` attribute so that it can be referenced by the BSF registry.

**Comment by wolenetz** [comment]
@mwatson2 - please take a look, or is @tidoust's prior approval sufficient? Thanks!

**Review by mwatson2 — APPROVED** [review]
Looks good! The only thing I noticed - which exists in the pre-existing text and so is not a comment on this PR - is that some of these variables have explicitly stated types (boolean / TimeRanges) and some do not.

**Comment by wolenetz** [comment]
> Looks good! The only thing I noticed - which exists in the pre-existing text and so is not a comment on this PR - is that some of these variables have explicitly stated types (boolean / TimeRanges) and some do not.

Thanks for the review. I too noticed some types missing. Some are simple, others like the "track buffer" concept have less strongly typed information, as it is left more to implementations. Possibly this is an area of improvement in the spec though, especially if things like buffered media introspection API is landed (where the notion of an app-visible "track buffer" object might make sense -- I've added a note around this to #259 ).

**Pull request merged**
