### PR TITLE
Remove createObjectURL extension

### LINKED ISSUE #211: URL.createObjectURL IDL is wrong (no overload across partial interfaces)
https://heycam.github.io/webidl/#idl-overloading

>Operations must not be overloaded across interface, partial interface, interface mixin, and partial interface mixin definitions.
>
>For example, the overloads for both f and g are disallowed:
>
>```webidl
>[Exposed=Window]
>interface A {
>  void f();
>};
>
>partial interface A {
>  void f(double x);
>  void g();
>};
>
>partial interface A {
>  void g(DOMString x);
>};
>```

Currently the MSE spec is adding an overload for `URL.createObjectURL` by a partial interface.

```webidl
[Exposed=Window]
partial interface URL {
    static DOMString createObjectURL(MediaSource mediaSource);
};
```

We should probably fix this in the [File API](https://w3c.github.io/FileAPI/#dfn-createObjectURL) spec.

### PR DESCRIPTION
**Pull request by saschanaz**
A followup after https://github.com/w3c/FileAPI/pull/103.

The overload has been merged into the File API spec so we can remove the extension.

Closes #211

***
<a href="https://pr-preview.s3.amazonaws.com/saschanaz/media-source/pull/229.html" title="Last updated on Mar 24, 2021, 12:58 AM UTC (b1fd43a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/media-source/229/2a413f9...saschanaz:b1fd43a.html" title="Last updated on Mar 24, 2021, 12:58 AM UTC (b1fd43a)">Diff</a>

### CODE REVIEW

**Comment by saschanaz** [comment]
Marked as non substantive for IPR from ash-nazg.

**Comment by foolip** [comment]
I just ran into the same issue. @wolenetz @mwatson2 can either of you review this?

**Comment by foolip** [comment]
@tidoust I see you recently made a change to this spec. Can you help get this merged?

**Comment by wolenetz** [comment]
@foolip, @tidoust - I'll merge this. The MSE-in-Workers feature (#175) may require some clarification about auto-revocation behavior (likely to be auto-revoke upon successful attachment to a media element), but that can come with that feature's specification in MSE.

**Comment by wolenetz** [comment]
@tidoust, spec-prod didn't like the result: https://github.com/w3c/media-source/actions/runs/768485056.
I'd like to learn more about spec-prod, so will investigate, but if it's something obvious don't hesitate to let me know :)

**Comment by saschanaz** [comment]
@wolenetz It's a resent regression from ReSpec https://github.com/w3c/respec/pull/3458, I'll file an issue there.

**Pull request merged**
