### PR TITLE
Fix #60: Relax WebM bytestream format's random access point definition

### LINKED ISSUE #60: WebM bytestream format is too restrictive around "random access points"
The current text: "A SimpleBlock element with its Keyframe flag set signals the location of a random access point for that track. Media segments containing multiple tracks are only considered a random access point if the first SimpleBlock for each track has its Keyframe flag set. The order of the multiplexed blocks must conform to the WebM Muxer Guidelines."

This has multiple overly-restrictive pieces that could be relaxed, given the robustness of the coded frame processing algorithm. I suggest:
1) Replacing the first sentence with something like "A random access point for a track is signalled by a SimpleBlock element with its Keyframe flag set for that track, or a BlockGroup element having no ReferenceBlock elements for that track."
2) Drop the second sentence; use (1) and the coded frame processing algorithm. Keep the third sentence as-is.

Do these changes relax that bytestream spec too much to achieve reliable interoperability?

### PR DESCRIPTION
**Pull request by wolenetz**

### CODE REVIEW

**Comment by wolenetz** [comment]
@jdsmith3000 @plehegar Please take a look.
Note that this contains a couple other changes to the MSE webm bytestream format:
1) Editors list update (OK'ed with @acolwell)
2) Various SOTD changes that automatically occurred since the last generation was over a year ago. (Updated process document reference, copyright date, etc.)

IIUC, this particular spec document is still OK to take even a potentially substantive change, even now (after the MSE v1 deadline of June 9th, yesterday). Please confirm.

**Comment by wolenetz** [comment]
For review assistance, here's an html-diff of this current PR vs current gh-pages version:
http://services.w3.org/htmldiff?doc1=http%3A%2F%2Frawgit.com%2Fw3c%2Fmedia-source%2Fd8f901f22e756dcc9f6ecd5d1216862b9f602623%2Fwebm-byte-stream-format.html&doc2=http%3A%2F%2Frawgit.com%2Fw3c%2Fmedia-source%2F36f152b6ede5b79a3d6391dd1118bd8448b6de5d%2Fwebm-byte-stream-format.html

**Comment by wolenetz** [comment]
@jdsmith3000 very friendly ping :)

Note, I'll be producing a PR shortly that attempts to fix #97, too.

**Comment by wolenetz** [comment]
@jdsmith3000 ping - please review this PR.
If I don't hear back by EOD PDT Monday, June 20, I plan to assume this change is good and will merge it then.

**Comment by wolenetz** [comment]
From chat, @jdsmith3000 will be reviewing this by EOD Tuesday, June 21.

**Comment by paulbrucecotton** [comment]
@jdsmith3000 - Was this PR reviewed?

**Comment by jdsmith3000** [comment]
I've reviewed the change.  LGTM.

**Comment by jdsmith3000** [comment]
On Friday:

              I've reviewed the change. LGTM.

Jerry

**Comment by wolenetz** [comment]
Thanks for the review.

**Comment by wolenetz** [comment]
I'll update the date and merge this shortly today.

**Pull request merged**
